[package]
name = "psilo-font"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freetype-rs = "0.29.0"
msdfgen = {path="../msdfgen-rs/msdfgen", features = ["freetype-rs"]} #{version = "0.1.0", features = ["freetype-rs"]}
msdfgen-lib = "0.1.0"
log = "0.4"
libc = "0.2.116"
